package Biblioteca.GestionBibliotecaPackage;


/**
* Biblioteca/GestionBibliotecaPackage/ListaLibrosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Biblioteca.idl
* domingo 17 de marzo de 2024 18H07' CET
*/


// Definir un tipo secuencia para Libro
public final class ListaLibrosHolder implements org.omg.CORBA.portable.Streamable
{
  public Biblioteca.Libro value[] = null;

  public ListaLibrosHolder ()
  {
  }

  public ListaLibrosHolder (Biblioteca.Libro[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Biblioteca.GestionBibliotecaPackage.ListaLibrosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Biblioteca.GestionBibliotecaPackage.ListaLibrosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Biblioteca.GestionBibliotecaPackage.ListaLibrosHelper.type ();
  }

}
